import type { CharacterDef, FacilityDef, Role, Stat, Style } from "../types.ts";
export const BRAND = {
  name: "星むすび",
  suffix: "プロダクション",
  platform: "STAR LIVE",
  subtitle: "小さな事務所から、きみと大きな夢へ。",
};
export const STATS: Record<Stat, string> = {
  talk: "トーク",
  sing: "歌",
  project: "企画",
  fanService: "ファンサ",
  mental: "メンタル",
  endurance: "継続力",
  popularity: "人気",
};
export const STYLES: Record<
  Style,
  { name: string; icon: string; mult: number }
> = {
  TALK: { name: "雑談", icon: "☕", mult: 1 },
  SING: { name: "歌", icon: "♫", mult: 1.1 },
  PROJECT: { name: "企画", icon: "✦", mult: 1.05 },
  ENDURANCE: { name: "耐久", icon: "⚡", mult: 1.25 },
  COLLAB: { name: "コラボ", icon: "♡", mult: 1.15 },
};
const raw: [
  string,
  string,
  string,
  string,
  number[],
  Style,
  string,
  string,
  string,
][] = [
  [
    "hiyori",
    "天音ひより",
    "愛され新人",
    "#ed83a7",
    [72, 42, 55, 75, 65, 52, 48],
    "TALK",
    "N",
    "新規ファン獲得 +15%",
    "初配信の前に、挨拶を何度も練習していた。誰かの帰ってくる場所になりたい。",
  ],
  [
    "luna",
    "星乃ルナ",
    "歌姫の原石",
    "#9390e9",
    [45, 82, 48, 60, 58, 60, 50],
    "SING",
    "R",
    "歌配信成果 +20%",
    "夜空を見ながら作ったメロディーを、いつか大きなステージで。",
  ],
  [
    "akane",
    "紅羽アカネ",
    "負けず嫌い",
    "#e46c62",
    [56, 35, 78, 52, 74, 82, 46],
    "PROJECT",
    "R",
    "イベント中成果 +20%",
    "企画ノートはもう三冊目。「絶対、みんなを楽しませるから！」",
  ],
  [
    "mina",
    "白雪ミナ",
    "神対応",
    "#8cbdd9",
    [58, 55, 48, 88, 62, 55, 55],
    "TALK",
    "SR",
    "ファンサ由来ファン増加 +25%",
    "一度来てくれた人の好きなものを、こっそりノートに書いている。",
  ],
  [
    "rei",
    "黒羽レイ",
    "トークモンスター",
    "#7474a0",
    [88, 38, 62, 58, 38, 52, 62],
    "TALK",
    "SR",
    "雑談成果 +30%・疲労80以上に注意",
    "話題は尽きないけれど、配信の後は静かな屋上がお気に入り。",
  ],
  [
    "momo",
    "猫宮モモ",
    "マイペース",
    "#d9a371",
    [68, 55, 58, 70, 70, 65, 55],
    "TALK",
    "N",
    "疲労増加 −15%",
    "お昼寝とミルクティーが好き。焦らず、自分の歩幅で歩いていく。",
  ],
  [
    "ao",
    "水瀬アオ",
    "努力家",
    "#5cafbf",
    [42, 76, 52, 56, 63, 58, 42],
    "SING",
    "N",
    "レッスン成長 +25%",
    "誰もいない朝のレッスン室から、今日も歌声が聞こえる。",
  ],
  [
    "shion",
    "神楽シオン",
    "天才企画屋",
    "#ab85c3",
    [62, 44, 91, 55, 48, 55, 60],
    "PROJECT",
    "SSR",
    "企画成果 +35%・失敗ペナルティ1.5倍",
    "突拍子もない思いつきが、事務所のみんなを笑顔にする。",
  ],
  [
    "yui",
    "桜庭ユイ",
    "みんなの妹",
    "#e698b9",
    [72, 60, 62, 82, 72, 60, 62],
    "COLLAB",
    "SR",
    "コラボ成果 +25%",
    "先輩にも後輩にも、最初に話しかけるのはいつもユイ。",
  ],
  [
    "noa",
    "月城ノア",
    "鉄人",
    "#647ab8",
    [52, 58, 55, 52, 82, 92, 50],
    "ENDURANCE",
    "R",
    "耐久配信疲労 −30%",
    "長い配信の最後でも「もうちょっと一緒にいよう」と笑う。",
  ],
  [
    "ren",
    "火神レン",
    "一発逆転",
    "#d78351",
    [62, 45, 86, 48, 55, 72, 65],
    "PROJECT",
    "R",
    "成果の振れ幅 0.70〜1.50",
    "うまくいかなかった日も、明日の大成功を信じている。",
  ],
  [
    "leaf",
    "森野リーフ",
    "大器晩成",
    "#77ac86",
    [50, 50, 50, 50, 68, 68, 38],
    "TALK",
    "N",
    "Lv10以降のレベル成長 +50%",
    "小さな芽を育てるように、毎日の一歩を大切にしている。",
  ],
  [
    "sora",
    "晴空ソラ",
    "朝の一番星",
    "#85bfd1",
    [65, 55, 52, 67, 70, 65, 43],
    "TALK",
    "N",
    "毎日の活動で少しずつ成長",
    "朝のあいさつで、誰かの一日を明るくしたい。",
  ],
  [
    "sumire",
    "花咲スミレ",
    "小さな歌声",
    "#af90c2",
    [48, 75, 58, 60, 69, 62, 45],
    "SING",
    "R",
    "毎日の活動で少しずつ成長",
    "花に歌を聴かせるように、やさしく言葉を届ける。",
  ],
  [
    "kaito",
    "蒼月カイト",
    "青空プランナー",
    "#709dbd",
    [70, 50, 77, 52, 64, 71, 58],
    "PROJECT",
    "SR",
    "毎日の活動で少しずつ成長",
    "白い企画書を見ると、わくわくが止まらない。",
  ],
  [
    "koharu",
    "日向コハル",
    "ひだまりの声",
    "#ddb47a",
    [66, 63, 48, 73, 77, 63, 44],
    "TALK",
    "N",
    "毎日の活動で少しずつ成長",
    "配信後のありがとうを、一人ひとりに伝える。",
  ],
  [
    "rio",
    "音羽リオ",
    "虹色メロディー",
    "#bf91bd",
    [52, 86, 68, 63, 64, 70, 63],
    "SING",
    "SSR",
    "毎日の活動で少しずつ成長",
    "虹が出た日に作った歌が、はじまりの一曲だった。",
  ],
  [
    "nagi",
    "海原ナギ",
    "波音ラジオ",
    "#7fb8ad",
    [78, 50, 64, 66, 72, 68, 52],
    "TALK",
    "R",
    "毎日の活動で少しずつ成長",
    "静かな夜にも、ひとりじゃないと思える配信を。",
  ],
  [
    "towa",
    "時雨トワ",
    "夜ふかしの相棒",
    "#8c94b7",
    [64, 54, 72, 58, 80, 87, 50],
    "ENDURANCE",
    "SR",
    "毎日の活動で少しずつ成長",
    "物語のラストまで、一緒に歩いていたい。",
  ],
  [
    "riko",
    "若葉リコ",
    "夢の種まき",
    "#a0bd7e",
    [54, 52, 59, 63, 73, 76, 40],
    "PROJECT",
    "N",
    "毎日の活動で少しずつ成長",
    "大きな夢も、まずは小さな種から育てていく。",
  ],
  [
    "haruto",
    "陽向ハルト",
    "陽だまりの相棒",
    "#568caa",
    [74, 43, 57, 70, 68, 61, 46],
    "TALK",
    "N",
    "毎日の活動で少しずつ成長",
    "笑い声が似合う男性ライバー。『おかえり！ 今日も一緒に話そう』がいつもの挨拶。",
  ],
  [
    "itsuki",
    "奏木イツキ",
    "夜空のシンガー",
    "#6975aa",
    [49, 80, 54, 64, 68, 62, 49],
    "SING",
    "R",
    "毎日の活動で少しずつ成長",
    "弾き語りが好きな男性ライバー。眠れない夜に寄り添う歌を届けたい。",
  ],
  [
    "takumi",
    "橘タクミ",
    "ひらめき案内人",
    "#649d8e",
    [68, 42, 82, 59, 72, 67, 56],
    "PROJECT",
    "SR",
    "毎日の活動で少しずつ成長",
    "工作とゲーム企画が得意な男性ライバー。失敗も笑いに変えて、みんなを巻き込む。",
  ],
  [
    "hayate",
    "風間ハヤテ",
    "挑戦の伴走者",
    "#b58a64",
    [58, 48, 70, 61, 79, 87, 54],
    "ENDURANCE",
    "SR",
    "毎日の活動で少しずつ成長",
    "挑戦を最後まで楽しむ男性ライバー。休む日も大切にしながら、仲間と夢を追う。",
  ],
];
const MALE_IDS = ["haruto", "itsuki", "takumi", "hayate"];
export const STARTER_IDS = ["hiyori", "luna", "akane", "haruto"];
export const CHARACTERS: CharacterDef[] = raw.map(
  ([
    id,
    name,
    nickname,
    color,
    values,
    preferredStyle,
    rarity,
    description,
    bio,
  ]) => ({
    id,
    ...(MALE_IDS.includes(id) ? { gender: "male" as const } : {}),
    name,
    nickname,
    color,
    preferredStyle,
    rarity: rarity as CharacterDef["rarity"],
    trait: nickname,
    description,
    bio,
    stats: Object.fromEntries(
      Object.keys(STATS).map((k, i) => [k, values[i]]),
    ) as Record<Stat, number>,
  }),
);
export const PRICES = { N: 15000, R: 40000, SR: 100000, SSR: 250000 };
export const FACILITIES: FacilityDef[] = [
  {
    kind: "booth",
    name: "配信ブース",
    short: "配信ブース",
    icon: "🎙",
    color: "#b3a8ef",
    price: 40000,
    unlock: 1,
    description: "ライバー1人が配信できます。強化で配信成果アップ。",
  },
  {
    kind: "sing",
    name: "歌レッスン室",
    short: "歌レッスン",
    icon: "♫",
    color: "#b5c9ef",
    price: 60000,
    unlock: 3,
    description: "歌のレッスンを解放。撮影スタジオと隣接で歌ファン +15%。",
  },
  {
    kind: "talk",
    name: "トークレッスン室",
    short: "トーク室",
    icon: "☏",
    color: "#efb4c4",
    price: 60000,
    unlock: 3,
    description: "トークのレッスンを解放。企画室と隣接で企画事故率を軽減。",
  },
  {
    kind: "project",
    name: "企画会議室",
    short: "企画会議室",
    icon: "✦",
    color: "#f0cf92",
    price: 70000,
    unlock: 3,
    description: "企画レッスンを解放。みんなのアイデアが集まる場所。",
  },
  {
    kind: "rest",
    name: "休憩スペース",
    short: "休憩スペース",
    icon: "☁",
    color: "#b1dcd1",
    price: 35000,
    unlock: 1,
    description: "疲労を回復。カフェと隣接で回復 +20%。",
  },
  {
    kind: "cafe",
    name: "カフェ",
    short: "ほしぞらカフェ",
    icon: "☕",
    color: "#e3bfa2",
    price: 50000,
    unlock: 2,
    description: "休養時のMood回復を強化。",
  },
  {
    kind: "manager",
    name: "マネージャーデスク",
    short: "マネージャー",
    icon: "▣",
    color: "#9fc8df",
    price: 75000,
    unlock: 2,
    description: "配信ブースと隣接で、そのブースの売上 +10%。",
  },
  {
    kind: "scout",
    name: "スカウト室",
    short: "スカウト室",
    icon: "⌕",
    color: "#b8cde7",
    price: 100000,
    unlock: 4,
    description: "候補のレアリティ抽選を改善。SSR上限は10%。",
  },
  {
    kind: "goods",
    name: "グッズコーナー",
    short: "グッズコーナー",
    icon: "🎁",
    color: "#e6c79b",
    price: 120000,
    unlock: 10,
    description: "毎日、ファン数に応じたグッズ収入。",
  },
  {
    kind: "studio",
    name: "撮影スタジオ",
    short: "撮影スタジオ",
    icon: "📷",
    color: "#accfc4",
    price: 180000,
    unlock: 12,
    description: "歌レッスン室と隣接で歌配信ファン +15%。",
  },
  {
    kind: "reception",
    name: "受付",
    short: "ようこそ！",
    icon: "✿",
    color: "#e7bdba",
    price: 25000,
    unlock: 1,
    description: "事務所の顔。毎日のMood回復 +2。",
  },
  {
    kind: "desk",
    name: "社長デスク",
    short: "社長デスク",
    icon: "★",
    color: "#a9bfd1",
    price: 30000,
    unlock: 1,
    description: "社長のお気に入りの机。育成と経営の見守り席。",
  },
];
export const ROLES: Record<
  Role,
  { name: string; salary: number; description: string }
> = {
  MANAGER: {
    name: "マネージャー",
    salary: 30000,
    description: "疲労増加 −15% / 配信事故率 −1%",
  },
  SCOUT: {
    name: "スカウト",
    salary: 35000,
    description: "SR・SSR候補の出現率アップ",
  },
  TRAINER: {
    name: "トレーナー",
    salary: 40000,
    description: "レッスン成長 +1",
  },
  PROMOTER: { name: "広報", salary: 45000, description: "新規ファン +15%" },
  DESIGNER: {
    name: "デザイナー",
    salary: 35000,
    description: "イベント得点・案件報酬 +20%",
  },
};
export const RANKS = [
  "D",
  "C5",
  "C4",
  "C3",
  "C2",
  "C1",
  "B3",
  "B2",
  "B1",
  "A3",
  "A2",
  "A1",
  "S3",
  "S2",
  "S1",
];
export const SLOTS = [
  { name: "朝", icon: "☀", mult: 0.75 },
  { name: "昼", icon: "☀", mult: 0.85 },
  { name: "夕方", icon: "◒", mult: 1 },
  { name: "夜", icon: "☾", mult: 1.3 },
  { name: "深夜", icon: "✧", mult: 1.05 },
];
export const EVENTS = [
  { name: "新人スター発掘祭", style: "TALK" },
  { name: "歌うまフェス", style: "SING" },
  { name: "雑談王", style: "TALK" },
  { name: "耐久チャレンジ", style: "ENDURANCE" },
  { name: "企画配信バトル", style: "PROJECT" },
] as const;
export const NPCS = [
  "Bright Live",
  "Moon Production",
  "Galaxy Connect",
  "Dream Link",
  "Nova Studio",
  "Smile Works",
  "Star Wave",
  "Neo Live",
];
export const RANDOM_EVENTS = [
  "切り抜きがバズる",
  "新衣装が話題",
  "機材の定期点検",
  "ファンアートが話題",
  "神企画誕生",
  "コラボのお誘い",
  "体調良好",
  "レッスン絶好調",
  "スタッフからの提案",
  "メディア掲載",
  "トレンド企画発見",
  "ファン記念日",
  "手作りのお弁当",
  "差し入れが届いた",
  "ラジオ出演のお誘い",
  "新しいマイクを発見",
  "お部屋を模様替え",
  "配信記念日",
  "応援メッセージ到着",
  "朝練の成果",
  "星空観察会",
  "新曲のアイデア",
  "ご近所のお祭り",
  "事務所の大掃除",
  "ゲーム大会を企画",
  "リスナーの誕生日",
  "歌のリクエスト",
  "配信スタンプ完成",
  "おそろいの衣装",
  "夢のステージへ",
];
export const ACHIEVEMENTS = [
  ["stream", "はじめての配信", "配信を1回完了", 10000],
  ["scout", "新しい仲間", "初めてのスカウト", 10000],
  ["build", "夢の増築", "施設を1つ建設", 10000],
  ["train", "一歩ずつ、前へ", "レッスンを1回完了", 5000],
  ["fans100", "最初の100人", "総ファン数100人", 5000],
  ["fans1k", "広がる輪", "総ファン数1,000人", 10000],
  ["fans10k", "たくさんの居場所", "総ファン数10,000人", 30000],
  ["fans100k", "満天の星", "総ファン数100,000人", 100000],
  ["team5", "にぎやかな事務所", "所属5人", 30000],
  ["team10", "みんなのホーム", "所属10人", 80000],
  ["team15", "夢が集まる場所", "所属15人", 120000],
  ["level5", "人気事務所の卵", "事務所Lv5", 20000],
  ["level10", "人気事務所", "事務所Lv10", 50000],
  ["level20", "憧れの事務所", "事務所Lv20", 100000],
  ["level30", "大手事務所へ", "事務所Lv30", 300000],
  ["event", "はじめての舞台", "イベントに参加", 10000],
  ["win", "一番星", "イベント1位", 100000],
  ["s", "事務所のエース", "Sランク誕生", 150000],
  ["million", "大きな一歩", "月商100万G", 100000],
  ["all", "理想のオフィス", "全12種類の施設", 100000],
  ["viral", "見つけてくれてありがとう", "配信がバズる", 15000],
  ["love", "ずっと一緒に", "好感度100", 50000],
  ["month", "最初の1か月", "月末を迎える", 20000],
  ["streams100", "積み重ねた時間", "配信100回", 30000],
] as const;
export const CONFIG = {
  daySeconds: 45,
  saveKey: "hoshimusubi-save-v1",
  tileWidth: 84,
  tileHeight: 44,
  minZoom: 0.7,
  maxZoom: 1.8,
  historyLimit: 30,
};
export const capacity = (level: number) =>
  level >= 30
    ? 20
    : level >= 20
      ? 16
      : level >= 15
        ? 12
        : level >= 10
          ? 8
          : level >= 5
            ? 5
            : 3;
export const staffCapacity = (level: number) =>
  Math.min(8, 1 + Math.floor(level / 5));
export const mapSize = (level: number) =>
  level >= 30 ? 16 : level >= 20 ? 14 : level >= 10 ? 12 : level >= 4 ? 10 : 8;
export const neededExp = (level: number) =>
  Math.floor(100 * Math.pow(level, 1.45));
export const format = (n: number) => Math.floor(n).toLocaleString("ja-JP");
export const compact = (n: number) =>
  Math.abs(n) >= 1000000
    ? `${(n / 1000000).toFixed(1)}m`
    : Math.abs(n) >= 10000
      ? `${(n / 1000).toFixed(1)}k`
      : format(n);
